### ISSUE TITLE
Edit overlay tile

### ISSUE THREAD

**Issue by BlueYoshi-57EML** [thomasgoldstein/epicedit#12]
Can you please add a feature to edit overlays to change the coin placement in a overlay tile if it's possible? For example to make a overlay tile full of coins?

**Comment by thomasgoldstein** [comment]
The way EE manages overlay tiles is restricted, but this is by design, to keep things simple for the user. I just did not think the way it's done in MAKE made for a good user experience.

In EE, overlay patterns are hardcoded and are not configurable. Sadly, overlay pattern definitions do not exist in the ROM as far as I know, so they would need to be saved somewhere if we want to make them editable... unless we go for something like MAKE and just propose all combinations, but I can't think of a way to handle that in a user-friendly way. Anyway, no doubt there are ways to improve the way EE works regarding overlay tiles, but that sounds like much more work than I want to put into it. I would accept patches for such a feature, but I won't work on it myself. I will only work on low-hanging fruits or things I really care for.

Still, thanks for the suggestion.
