### ISSUE TITLE
Set a tile palette's over 8

### ISSUE THREAD

**Issue by BlueYoshi-57EML** [thomasgoldstein/epicedit#16]
Could it be possible to set a tile's palette over 8? I managed to do that by editing the tile/palette association in a hex editor, it works fine in-game but epic edit doesn't like it.

**Comment by thomasgoldstein** [comment]
I am confused. Why did I do it this way, and why did no one bring it up before?
I tried removing that limitation, and it works just fine. I guess I initially got confused by the fact track object palettes are limited to the 8 last palettes, and so I must have assumed road tiles were limited to the first 8 palettes (especially since the original game doesn't go beyond palette 8 for road tiles)...

I have just released EE 2.8.9, which contains the fix. Thanks for the report.
