### ISSUE TITLE
Bug on koopa beach Tiles

### ISSUE THREAD

**Issue by Cocatriz** [thomasgoldstein/epicedit#2]
There is a problem when you try to change the koopa beach tiles. Even loading the original, the game show the shallow water graphics bad. all the blue colored shallow water get from blue to totally white when the waves act. This is a shame because its the only stage where this happend and don't allow to load any koopa beach tile set, could you please fix this and make a perfect editor so? thanks!!! Best editor ever

**Comment by thomasgoldstein** [comment]
Somehow, I missed the fact people have been adding bugs here. Sorry for the delay.

This is known and not actually a bug. To sum things up, it's due to the fact the original game uses the same color across different color indexes within the palette, and then uses color cycling to simulate waves. When exporting tileset graphics as an image, you lose the color index information. This might not be clear, but to sum things up, you have 2 ways to work around this issue: either export and import the graphics as a binary file (which does retain the color indexes), or first make sure all colors within the palette are unique before changing the tileset graphics.

**Comment by thomasgoldstein** [comment]
@Cocatriz Epic Edit 2.9 has been released today. It contains a new solution to the problem you reported: exporting and importing tileset graphics as indexed images. This will preserve color indexes (as long as you use an editor which fully supports indexed images). It's been so long you might not care about hacking Super Mario Kart anymore, but I thought I'd spread the word.
